### ISSUE TITLE
Bring to Core JOSM

### ISSUE THREAD

**Issue by hallahan** [JOSM/geojson#10]
Has anybody considered just porting this to the main JOSM code base? This plugin is super straight-forward and opening GeoJSON in JOSM is a very common editing use case.

**Comment by floscher** [comment]
Yes, the plugin is not really complicated by itself. But it uses the external libraries `geojson-jackson`, `jackson-core`, `jackson-databind` and `jackson-annotations`, which JOSM core would then also need to depend on.

There is https://josm.openstreetmap.de/ticket/10564 , which was opened in 2014 to bring support for importing GeoJSON to the `opendata` plugin.

**Comment by don-vip** [comment]
Jackson is a no-go for inclusion in JOSM core, as we already embed [json-p as JSON library](https://github.com/eclipse-ee4j/jsonp). Once the plugin will migrate to this library it will be considered for inclusion.

**Comment by don-vip** [comment]
The GeoJson integration is followed up by this JOSM core ticket: https://josm.openstreetmap.de/ticket/10564

**Comment by don-vip** [comment]
Done in https://josm.openstreetmap.de/changeset/15424/josm
