### ISSUE TITLE
Convert plugin to json-p API

### ISSUE THREAD

**Issue by don-vip** [JOSM/geojson#16]
This plugin currently uses Jackson to convert GeoJSON. While it's surely easier to write it this way, it is a no-go for inclusion in JOSM core (#10), as JOSM already embeds [json-p as JSON library](https://github.com/eclipse-ee4j/jsonp). Once the plugin will migrate to this library it will be considered for inclusion.

**Comment by jreijn** [comment]
If it's still up for grab I would like to do this :-)

**Comment by don-vip** [comment]
Thank you @jreijn :+1: You're the first one to show up, please go ahead :) If you're new to JOSM development, here is the [developer guide](https://josm.openstreetmap.de/wiki/DevelopersGuide). Feel free to ask any question :)

**Comment by floscher** [comment]
@jreijn Great, yes go ahead.
For your information: The GeoJSON plugin can be built using either Ant or Gradle, you can choose which one to use. The developer guide mainly covers the Ant way, for documentation about building with Gradle see https://gitlab.com/floscher/gradle-josm-plugin#readme or ask me.

Happy Hacking!

**Comment by jreijn** [comment]
@floscher I'm not sure if you know about it, but I was wondering if there are any GeoJSON based POJOs available somewhere in the project? Otherwise I will create some myself.

**Comment by floscher** [comment]
@jreijn For GeoJSON primitives the classes from [Jackson](https://github.com/FasterXML/jackson-core)
were used: https://github.com/JOSM/geojson/blob/14eab01cf9a24f2e2bd8c18ff7f40fe613695778/src/main/java/org/openstreetmap/josm/plugins/geojson/DataSetBuilder.java#L10-L20 So yes, you can create your own for use with the json-p API.
If it's easily possible, maybe you could even directly create (J)OSM primitives without first instantiating objects representing the GeoJSON datastructure. But I'd leave that to you, how you want to implement it.

**Comment by jreijn** [comment]
@floscher yeah I noticed those, but they are dependent on an external library that's build for Jackson. I'll see what I can do.

**Comment by don-vip** [comment]
For reference you can take a look to [`OsmJsonReader`](https://github.com/openstreetmap/josm/blob/mirror/src/org/openstreetmap/josm/io/OsmJsonReader.java) core class (which reads an Overpass API JSON OSM file, not a GeoJson). It might be very similar.

**Comment by jreijn** [comment]
@don-vip wow great. Looks interesting!

**Comment by jreijn** [comment]
Sorry for the delay. I was seek for a week. Let me know if it requires further improvements. I've tried the plugin with several geo json files and it seems to work nicely.

**Comment by don-vip** [comment]
Don't be sorry, thanks a lot for your work! I'm going to take a look :)

**Comment by don-vip** [comment]
An optimization is missing: the jsonp classes should not be embedded into plugin jar file, as they are provided by JOSM core.

**Comment by jreijn** [comment]
Ah yes. You are right. I guess they can use scope provided. Do you want me to create a new PR for that?
