### ISSUE TITLE
Add GeoJSON download task

### ISSUE THREAD

**Issue by don-vip** [JOSM/geojson#21]
The plugin allows to open json/geojson files, even compressed thanks to #18 

To bring a native GeoJson JOSM experience, a download task must be added on the model of [DownloadOsmCompressedTask](https://github.com/openstreetmap/josm/blob/6d4bcded2b6c2efb1a0f12354cf7493bcd6f4e42/src/org/openstreetmap/josm/actions/downloadtasks/DownloadOsmCompressedTask.java) using `OpenLocationAction.addDownloadTaskClass`. Example for another plugin:
```java
MainApplication.getMenu().openLocation.addDownloadTaskClass(CadastreDownloadTask.class);
```

With this change we will be able to open an URL like [this](https://cadastre.data.gouv.fr/data/etalab-cadastre/2018-06-29/geojson/communes/31/31555/cadastre-31555-batiments.json.gz) via drag and drop or `Ctrl-L`.

**Comment by don-vip** [comment]
@floscher comments in #24 must be addressed. Can you please submit a new one?

**Comment by floscher** [comment]
I'll commit the translation issues directly. Probably the big one needs also changes in core (because the overridden method instantiates `OsmDataLayer`, but the overriding method needs to instantiate the subclass `GeoJsonLayer`).

**Comment by floscher** [comment]
The issues should now be fixed.
