### ISSUE TITLE
Importing 3D coordinates into JOSM as CSV-files

### ISSUE THREAD

**Issue by nnuk** [JOSM/geojson#27]
Hi,

I was adding some coordinates as a CSV file to my map with the help of OpenData plugin but they had only latitude and longitude which is normal. If I want to add a point which has some height too like in a multi storey parking, how can i do that in JOSM.
Thanks.

**Comment by don-vip** [comment]
This bug tracker is for GeoJson plugin and your question is completely out of subject. See my answer on your [duplicate post](https://josm.openstreetmap.de/ticket/17063).
