### ISSUE TITLE
Freezes half way through loading geojson

### ISSUE THREAD

**Issue by harry-wood** [JOSM/geojson#3]
This plugin isn't working at all for me. After selecting a file it shows a progress bar "Loading json file..." but always stops half way along and freezes up

By freezing up I mean, I can hear my CPU fan going, but nothing's happening. At this point the 'Cancel' button doesn't work, but I can close the dialog box to continue. If I run JSON in a terminal I see this
```
2016-11-15 23:23:17.046 INFO: Open file: /Users/harrywood/Desktop/restaurants-goswell-rd.geojson (2181 bytes)
2016-11-15 23:23:17.046 INFO: Parsing GeoJSON: /Users/harrywood/Desktop/restaurants-goswell-rd.geojson
```

It also says I'm using `plugin 'geojson' (version 43)`

At first I tried this with quite a large geojson file downloaded from the Tasking Manager export feature. Then I tried a much smaller simpler file: [restaurants-goswell-rd.geojson](https://gist.githubusercontent.com/harry-wood/e96599042264e7f78cbb/raw/9508ff713a254b093d5ce43d1c421847ecb36503/restaurants-goswell-rd.geojson)  Same problem either way.

**Comment by simon04** [comment]
This is a core bug, tracked as https://josm.openstreetmap.de/ticket/13985 and fixed in https://josm.openstreetmap.de/changeset/11261/josm
