### ISSUE TITLE
GeoJSON no longer permits projections other than WGS84

### ISSUE THREAD

**Issue by simon04** [JOSM/geojson#5]
In August, GeoJSON has been released as RFC 7946: ​https://tools.ietf.org/html/rfc7946

Relating to ​[section 4](https://tools.ietf.org/html/rfc7946#section-4), only WGS84 is specified as CRS.

The [​appendix](https://tools.ietf.org/html/rfc7946#appendix-B) explicitly states: 

>   o  Specification of coordinate reference systems has been removed, i.e., the "crs" member of [GJ2008] is no longer used.

See also JOSM core ticket: https://josm.openstreetmap.de/ticket/13358

**Comment by hallahan** [comment]
The nice thing about removing the CRS stuff is that we will no longer require geotools. geotools requires a bunch of other jars. It's kinda a mess. If we culled out that CRS stuff, this plugin will then have no dependent jars.

JARs that get installed:

```
ejml.jar
geotools.jar
jts.jar
```

jts, for example, is completely unnecessary.

**Comment by floscher** [comment]
There are even more required plugins:
* `opendata`
  * `apache-commons`
  * `ejml`
  * `geotools`
    * `ejml`
    * `jts`
  * `jts`
  * `utilsplugin2`
* `geotools`
  * `ejml`
  * `jts`

So removing `geotools` from the required plugins wouldn't help much. The `opendata` plugin would still require `geotools`.

But as far as I can see, although the `opendata` plugin is in the list of required plugins, it is never used, so it could even be removed without changing the plugin?!

And I totally agree, that it would be great to also drop the dependency on `geotools`.
