### ISSUE TITLE
There is something wrong with the format after conversion

### ISSUE THREAD

**Issue by lileilei** [JOSM/geojson#6]
geometry.type = "LineString"  .There will be a map cracking problems

 mapbox need to type is "Polygon"。I judge according to the example: https://www.mapbox.com/help/choropleth-studio-gl-pt-1

**Comment by simon04** [comment]
This plugin is for reading GeoJSON files. If you think the format generated/written by JOSM is incorrect, open a issue here: https://josm.openstreetmap.de/newticket
